CREATE DATABASE odontoClinic CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  senha VARCHAR(255) NOT NULL,
  cargo INT(5) DEFAULT NULL,
  telefone VARCHAR(15) DEFAULT NULL,
  cep VARCHAR(9) DEFAULT NULL,
  rua VARCHAR(100) DEFAULT NULL,
  numero VARCHAR(10) DEFAULT NULL,
  bairro VARCHAR(100) DEFAULT NULL,
  cidade VARCHAR(100) DEFAULT NULL,
  estado VARCHAR(2) DEFAULT NULL,
  foto VARCHAR(255) DEFAULT NULL,
  ativo TINYINT(1) DEFAULT 1,
  data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE cargos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE usuarios 
ADD CONSTRAINT fk_cargo 
FOREIGN KEY (cargo) REFERENCES cargos(id) 
ON DELETE SET NULL 
ON UPDATE CASCADE;
